### ISSUE TITLE
Consider not defaulting to /tmp

### ISSUE THREAD

**Issue by severen** [dbermond/screencast#3]
I consider `/tmp` to be a bad default for storing the intermediate raw video, since as the README itself says, it is usually a ramdisk filesystem in modern Linux distributions. Due this, as you are probably aware, it is possible to fill up the system's memory and send it grinding to a halt if you use too much space. (it just bit me while I was playing around with Screencast and I had to force shut down my system as a result.) Ideally `/tmp` is for small, inconsequential files, _not_ a temporary cache for raw video.

I believe a better location would be something like `$XDG_CACHE_HOME/screencast`.

**Comment by anthraxx** [comment]
Besides that, it opens up a symlink attack vulnerability via non secure usage of /tmp allowing on a multi-user system to delete arbitrary user owned files or steal arbitrary secret data like ssh or gnupg keys
https://github.com/dbermond/screencast/blob/HEAD/src/settings_general.sh#L31
https://github.com/dbermond/screencast/blob/HEAD/src/system.sh#L31
https://github.com/dbermond/screencast/blob/HEAD/src/system.sh#L40

**Comment by dbermond** [comment]
@severen Thank you for the interest in this software.

I was pointed by @anthraxx some weeks ago about this issue. I'll implement this change as soon as possible, probably by using mktemp as suggested by him. Right now I'm having some busy weeks.
