### ISSUE TITLE
Long waiting before start of recording

### ISSUE THREAD

**Issue by schef** [dbermond/screencast#4]
Hi,
is there a reason why recording starts after maybe 40s when i hit the command?
I execute `screencast ./myvideo2.mp4` and i get the last line `[ screencast ] recording` after that i wait for 40s and then i get `qffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers`.
Thanks

**Comment by dbermond** [comment]
Your message shows `qffmpeg`. This is not supported and you should use [ffmpeg](https://ffmpeg.org).

What is your operating system?

Does the delay disappear if you disable desktop notifications with the `-n` (`--no-notifications`) option?

If not, try also to disable audio recording with `-a none` (or with `-i none`) and see if it helps.

**Comment by schef** [comment]
When i start with `-n` it starts instantly. Thanks :)

**Comment by dbermond** [comment]
Good to know that it worked.

It looks like that this is not a screencast bug. Something on your system is causing the delay in the `notify-send` command. You need to experiment with it to find out. You can try to run something like this and see what's going on:

```
$ notify-send --urgency='normal' --expire-time='1700' --icon='media-record' screencast 'test message'
```
