### ISSUE TITLE
PulseAudio: Record Playback instead of Output Devices

### ISSUE THREAD

**Issue by schef** [dbermond/screencast#6]
Is it possible to select a specific Playback device instead of Output device. It would be much more practical.
And in current implementation how do you select a specific PulseAudio Device and not the first selected?
Thanks

**Comment by dbermond** [comment]
Do you mean recording audio from an output device? Like recording audio from a running application that is outputting/playing audio?

**Comment by dbermond** [comment]
Closing as there is no answer from the OP after a considerable period of time (almost 6 months now).

Fell free to request a reopen if needed.
