### ISSUE TITLE
error: unknown option '--display' 

### ISSUE THREAD

**Issue by 0x41mmarVM** [dbermond/screencast#8]
First, thank you for this wonderful piece of software!

Issue: title says it all, I'm trying to specify an X11 display to record using the --display option, but screencast can't recognize it.
`[ screencast ] error: unknown option '--display'`

I installed it using the ubuntu package, and the reported version is 1.5.0.

**Comment by 0x41mmarVM** [comment]
Ok, got it. I see that option was created after the release in the repo. Time to compile from source.

**Comment by dbermond** [comment]
Thank you for the interest in this software.

Yes, currently the `--display` option is present only on git master. Version 1.5.0 does not have it.
