### ISSUE TITLE
Get lossless MKV, no encoding

### ISSUE THREAD

**Issue by 0x41mmarVM** [dbermond/screencast#9]
Is it possible to just get the FFV1 MKV file with no encoding?
I can see the file ends up in my tmp folder with the name {my_output_name}-lossless.mkv after the second stage encoding is done, which is great, but can I skip the second stage altogether? 
I'm open to modifying code if that seems best, but I'd appreciate a quick pointer on what you think might be the fastest way to do it.

**Comment by dbermond** [comment]
You can use the [`--keep`/`-K`](https://github.com/dbermond/screencast/tree/v1.5.0#-k---keep) option for getting the lossless video, but skipping the  encoding step is not supported.

Can you please elaborate on the reasons you have for skipping the encoding?

**Comment by 0x41mmarVM** [comment]
I'm creating a container that requires some configurability, in certain cases it is desirable to do the encoding later, on a faster machine. I realize the benefits of using Screencast as opposed to directly interfacing with ffmpeg are reduced in this case, but it's not the default usage.
